import { ShipDef, UpgradeCardDef } from './types';

export const SHIPS: ShipDef[] = [
  {
    id: 'striker',
    name: 'חץ הברק (Striker)',
    subName: 'סייר קרבי מהיר',
    description: 'ספינה זריזה במיוחד בעלת קצב ירי מואץ ודיוק קטלני. מתאימה לתמרונים מהירים.',
    color: '#06b6d4',
    accentColor: '#38bdf8',
    maxHp: 100,
    speed: 5.5,
    fireRate: 4.2,
    specialTrait: '+25% קצב אש בסיסי, מהירות תנועה גבוהה',
  },
  {
    id: 'titan',
    name: 'מבצר הפלזמה (Titan)',
    subName: 'סיירת משוריינת כבדה',
    description: 'מבצר מעופף עם שריון עבה במיוחד, מד חיים כפול ומגן פלזמה סביבתי שמוחץ אויבים סמוכים.',
    color: '#f59e0b',
    accentColor: '#fbbf24',
    maxHp: 180,
    speed: 4.0,
    fireRate: 3.0,
    specialTrait: '+80% נקודות חיים, מגן אורביטלי פעיל מהפתיחה',
  },
  {
    id: 'spectre',
    name: 'נובה קוואנטית (Spectre)',
    subName: 'משחתת אנרגיה אפלה',
    description: 'ספינה ניסיונית המפעילה פעימות אנרגיה וטילים מונחי-מטרה, בעלת פוטנציאל פגיעה קריטית עצום.',
    color: '#a855f7',
    accentColor: '#c084fc',
    maxHp: 90,
    speed: 4.8,
    fireRate: 3.5,
    specialTrait: '+30% סיכוי לפגיעה קריטית כפולה וטילי מעקב מהפתיחה',
  },
];

export const UPGRADES: UpgradeCardDef[] = [
  {
    id: 'multiShot',
    name: 'מטח מפוצל (Multi-Shot)',
    description: 'מוסיף קליע לייזר נוסף לכל מטח ירי בזווית מניפה רחבה.',
    icon: 'Layers',
    rarity: 'rare',
    maxLevel: 4,
  },
  {
    id: 'fireRate',
    name: 'קצב אש מוגבר (Overdrive)',
    description: 'מאיץ את מהירות הירי של הספינה ב-25%.',
    icon: 'Zap',
    rarity: 'common',
    maxLevel: 5,
  },
  {
    id: 'homingMissile',
    name: 'טילי מעקב חכמים (Seeker Missiles)',
    description: 'משגר אוטומטית טילי פלזמה שרודפים אחרי מטרות קרובות ומתפוצצים.',
    icon: 'Crosshair',
    rarity: 'rare',
    maxLevel: 4,
  },
  {
    id: 'orbitalShield',
    name: 'מגן אורביטלי (Plasma Orbs)',
    description: 'כדורי פלזמה מסתובבים סביב הספינה ומשמידים כל אויב או קליע שמתקרב.',
    icon: 'Shield',
    rarity: 'epic',
    maxLevel: 4,
  },
  {
    id: 'laserBeam',
    name: 'קרן לייזר חודרת (Piercing Beam)',
    description: 'קליעי הלייזר שלך חודרים דרך שורות אויבים מבלי להיעלם.',
    icon: 'Flame',
    rarity: 'rare',
    maxLevel: 3,
  },
  {
    id: 'maxHp',
    name: 'שריון ננו-מחוזק (Hull Plating)',
    description: 'מוסיף +35 נקודות חיים מרביות ומרפא 30 HP באופן מיידי.',
    icon: 'Heart',
    rarity: 'common',
    maxLevel: 5,
  },
  {
    id: 'magnet',
    name: 'מגנט קוואנטי (Magnetic Core)',
    description: 'מגדיל באופן משמעותי את טווח משיכת גבישי ה-EXP לספינה.',
    icon: 'Magnet',
    rarity: 'common',
    maxLevel: 4,
  },
  {
    id: 'moveSpeed',
    name: 'מנועי דחף יוניים (Ion Thrusters)',
    description: 'משפר את מהירות התנועה והתמרון של הספינה ב-18%.',
    icon: 'Wind',
    rarity: 'common',
    maxLevel: 4,
  },
  {
    id: 'critChance',
    name: 'היפר-קריטי (Critical Laser)',
    description: 'מעלה את הסיכוי לפגיעה קריטית (נזק כפול מוגדל פי 2.5) ב-18%.',
    icon: 'Sparkles',
    rarity: 'rare',
    maxLevel: 4,
  },
  {
    id: 'droneCompanion',
    name: 'רחפן ליווי קרבי (Attack Drone)',
    description: 'רחפן קרב אוטונומי הטס לצדך וממטיר אש רציפה על מטרות אויב.',
    icon: 'Radio',
    rarity: 'epic',
    maxLevel: 3,
  },
];
